One-dimensional Array: [1, 5, 2, 0]
Two-dimensional Array: [[1, 2, 3], [4, 5, 6]]

ndarray: represents N-deminsional array. 

Arrays have restrictions: Ex.
 - all elements of the array must be the same type of data. 
 - Once created, the total size of the array can’t change
 - The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

Thes conditions make NumPy make array's faster and more memory efficient. 

NumPy gives speed and tools to handle largescale operations efficiently 

In [9]:
import numpy as np

print(np.__version__) # Prints current version of numpy

a = np.array([1, 2, 3, 4, 5, 6])

print(a) # output [1 2 3 4 5 6]
print(a[0]) # output 1

a[0] = 10 # replaced the first element with 10
print(a) # output [10  2  3  4  5  6]



2.4.4
[1 2 3 4 5 6]
1
[10  2  3  4  5  6]


In [12]:
array = np.array([1, 2, 3, 4])

array = array * 2 # Multiplies each element of the array by 2
print(array) # output [2 4 6 8]

[2 4 6 8]


In [ ]:
# 0D array
array = np.array('A')

# 1D array
array_1 = np.array(['A', 'B', 'C'])

# 2D array
array_2 = np.array([['A', 'B', 'C'], 
                    ['D', 'E', 'F'], 
                    ['G', 'H', 'I']])
# 3D array
array_3 = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

#.ndim attribute returns the number of dimensions of the array
print(array.ndim) # output 0
print(array_1.ndim) # output 1
print(array_2.ndim) # output 2
print(array_3.ndim) # output 3



0
1
2
3


In [18]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.shape) # output (3, 3, 3)

(3, 3, 3)


shape produces 3 outputs (layers, rows, columns)

first layer: 
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

second layer: 
[['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

third layer: 
[['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

In [ ]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],])

print(array.shape) # output (2, 3, 3)

(2, 3, 3)


In [20]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

# layer, row, column
print(array[0, 0, 0]) # output A
print(array[0, 1, 2]) # output F
print(array[1, 2, 1]) # output Q
print(array[2, 1, 0]) # output V

A
F
Q
V
