One-dimensional Array: [1, 5, 2, 0]
Two-dimensional Array: [[1, 2, 3], [4, 5, 6]]

ndarray: represents N-deminsional array. 

Arrays have restrictions: Ex.
 - all elements of the array must be the same type of data. 
 - Once created, the total size of the array can’t change
 - The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

Thes conditions make NumPy make array's faster and more memory efficient. 

NumPy gives speed and tools to handle largescale operations efficiently 

In [9]:
import numpy as np

print(np.__version__) # Prints current version of numpy

a = np.array([1, 2, 3, 4, 5, 6])

print(a) # output [1 2 3 4 5 6]
print(a[0]) # output 1

a[0] = 10 # replaced the first element with 10
print(a) # output [10  2  3  4  5  6]



2.4.4
[1 2 3 4 5 6]
1
[10  2  3  4  5  6]


In [12]:
array = np.array([1, 2, 3, 4])

array = array * 2 # Multiplies each element of the array by 2
print(array) # output [2 4 6 8]

[2 4 6 8]


# Multidimensional Arrays

In [ ]:
# 0D array
array = np.array('A')

# 1D array
array_1 = np.array(['A', 'B', 'C'])

# 2D array
array_2 = np.array([['A', 'B', 'C'], 
                    ['D', 'E', 'F'], 
                    ['G', 'H', 'I']])
# 3D array
array_3 = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

#.ndim attribute returns the number of dimensions of the array
print(array.ndim) # output 0
print(array_1.ndim) # output 1
print(array_2.ndim) # output 2
print(array_3.ndim) # output 3



0
1
2
3


In [18]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

print(array.shape) # output (3, 3, 3)

(3, 3, 3)


# Shape produces 3 outputs (layers, rows, columns)

## first layer: 
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

## second layer: 
[['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

## third layer: 
[['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]
    1st row         2nd row             3rd row
    3 col.          3 col.              3 col. 

In [ ]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],])

print(array.shape) # output (2, 3, 3)

(2, 3, 3)


In [20]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

# layer, row, column
print(array[0, 0, 0]) # output A
print(array[0, 1, 2]) # output F
print(array[1, 2, 1]) # output Q
print(array[2, 1, 0]) # output V

A
F
Q
V


In [ ]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])

word = array[0, 0, 2] + array[0, 0, 0] + array[1, 2, 2]

print(word) # output CAR

CAR


# Slicing

In [ ]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# array[start:end:step]
# start: the index to start slicing from (inclusive)
# end: the index to end slicing at (exclusive)
# step: the step size to use when slicing (default is 1)

print(array[0:4:2]) # output [[ 1  3]

print()

print(array[::2]) # output [[ 1  3]

print()

print(array[-1::-1]) # output [[16 15 14 13] [12 11 10 9] [8 7 6 5] [4 3 2 1]]
print()
print(array[::-2]) # output [[13 14 15 16] [5 6 7 8]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 9 10 11 12]]

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

[[13 14 15 16]
 [ 5  6  7  8]]


In [54]:
# Column Selection

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# First column has index 0, second column has index 1, and so on.

print(array[:, 0]) # output [1 5 9 13]
print(array[:, 1]) # output [2 6 10 14]

print()

print(array[:, 0:3]) # prints the first three columns of the array
print()
print(array[:, 1:4]) # prints the second through fourth columns of the array

print(array[:, 1::2]) # prints every other column of the array, starting with the first column
print(array[:, ::-2]) # prints every other column of the array, starting with the last column

[ 1  5  9 13]
[ 2  6 10 14]

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [ ]:
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# Combining row and column selection

print(array[0:2, 0:2]) # output [[1 2] [5 6]]
print()
print(array[0:2, 2:4]) # output [[3 4] [7 8]]
print()
print(array[2:4, 2:4]) # output [[11 12] [15 16]]
print()
print(array[1:3, 0:4]) # output [[5 6 7 8] [9 10 11 12]]

[[1 2]
 [5 6]]

[[3 4]
 [7 8]]

[[11 12]
 [15 16]]

[[ 5  6  7  8]
 [ 9 10 11 12]]


# Arithmetic

In [66]:
# Scalar Arithmetic

array = np.array([1, 2, 3])

print(array + 1) # output [2 3 4]
print(array - 2) # output [-1 0 1]
print(array * 3) # output [3 6 9]
print(array / 4) # output [0.25, 0.5, 0.75]
print(array ** 5) # output [1 32 243]

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
# Vectorized math functions

array = np.array([1.01, 2.5, 3.99])


print(np.sqrt(array)) # output [1.00498756 1.58113883 1.99749844]
print(np.ceil(array)) # output [2. 3. 4.]
print(np.floor(array)) # output [1. 2. 3.]

[1.00498756 1.58113883 1.99749844]
[2. 3. 4.]
[1. 2. 3.]


In [ ]:
# More Vectorized Math Functions

# Exercise: Calculate the area of circles with different radii using the formula A = πr^2

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2) # output [ 3.14159265 12.56637061 28.27433388]

[ 3.14159265 12.56637061 28.27433388]


In [74]:
# Element-wise Arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2) # output [5 7 9]
print(array1 - array2) # output [-3 -3 -3]
print(array1 * array2) # output [4 10 18]
print(array1 / array2) # output [0.25 0.4 0.5]
print(array1 ** array2) # output [ 1 32 729]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [79]:
# Comparison Operators

scores = np.array([91, 55, 100, 73, 82, 63])

print(scores == 100) # output [False False  True False False False]
print(scores >= 60) # output [ True False  True  True  True  True]
print(scores < 60) # output [False  True False False False False]

scores[scores < 60] = 0 # replace all scores less than 60 with 0
print(scores) # output [91  0 100 73 82 63]

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  63]


# Broadcasting
## Allows Numpy to perform operations on arrays with different shapes
## It virtually expands dimensions so they can match larger array's shape

### Dimensions either have same size
#### Or 
### One of the dimensions has a size of 1


In [ ]:
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape) # output (1, 4)
print(array2.shape) # output (4, 1)

print() 

print(array1 * array2) # output [[ 1  2  3  4] [ 2  4  6  8] [ 3  6  9 12] [ 4  8 12 16]]

(1, 4)
(4, 1)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
array1 = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape) # output (2, 4)
print(array2.shape) # output (4, 1)

# Error because the first column of array1 has 2 elements, while the first column of array2 has 4 elements.
# Rules: - The number of columns in the first array must match the number of rows in the second array for matrix multiplication to work.
# or 
# The the dimension of the first array must be 1, or the dimension of the second array must be 1 for element-wise multiplication to work.
print(array1 * array2)

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [ ]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape) # output (1, 10)
print(array2.shape) # output (10, 1)

print() 

print(array1 * array2) # Output: 10 x 10
 


(1, 10)
(10, 1)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


# Aggregate Functions
## Summarizes Data and typically returns a single value

In [ ]:
array = np.array([[1, 2, 3, 4, 5, ], 
                  [6, 7, 8, 9, 10, ]])

print(np.sum(array)) # sum of array elements, output 55
print(np.mean(array)) # mean of the array elements, output 5.5
print(np.std(array)) # standard deviation of the array
print(np.var(array)) # square of the standard deviation, output 8.25
print(np.min(array)) # output 1
print(np.max(array)) # output 10
print(np.argmin(array)) # position of the minimum element in the array, output 0
print(np.argmax(array)) # position of the maximum element in the array, output 9

55
5.5
2.8722813232690143
8.25
1
10


In [ ]:
array = np.array([[1, 2, 3, 4, 5, ], 
                  [6, 7, 8, 9, 10, ]])

print(np.sum(array, axis=0)) # sum of each column, output [7 9 11 13 15]
print(np.sum(array, axis=1)) # sum of each row, output [15, 40]

[ 7  9 11 13 15]
[15 40]


# Filtering
## Process of selecting elements from an array that match a given condition

In [ ]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

# Boolean indexing allows you to select elements of an array based on a condition.
# flattens data

teenagers = ages[ages < 18] # selects all elements of the array that are less than 18
adults = ages[(ages >= 18) & (ages < 65)] # selects all elements of the array that are greater than or equal to 18 and less than 65
seniors = ages[ages >= 65] # selects all elements of the array that are greater than or equal to 65 
evens = ages[ages % 2 == 0] # selects all elements of the array that are even numbers   
odds = ages[ages % 2 != 0] # selects all elements of the array that are odd numbers

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65], 
                 [39, 22, 15, 99, 18, 19, 20, 21]])

# where(condition, x, y) returns an array with elements from x where condition is True, and elements from y where condition is False.
# where function will preserve original shape of data, but slower than using boolean indexing
adults = np.where(ages >= 18, ages, -1) # replaces all elements of the array that are less than 18 with -1, and keeps all other elements unchanged
print(adults)

[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]
